/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __FPRINTD_MARSHAL_MARSHAL_H__
#define __FPRINTD_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING,BOOLEAN (/home/hadess/Projects/jhbuild/fprintd/src/fprintd-marshal.list:1) */
extern
void fprintd_marshal_VOID__STRING_BOOLEAN (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);


G_END_DECLS

#endif /* __FPRINTD_MARSHAL_MARSHAL_H__ */
